# Generated by Django 2.2.3 on 2019-07-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Repository name', max_length=100)),
                ('description', models.TextField(help_text='Repository description text')),
                ('url', models.CharField(help_text='Repository git url', max_length=200)),
                ('language', models.CharField(help_text='Programming language name', max_length=50)),
                ('watchers_count', models.IntegerField()),
            ],
        ),
    ]
